import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "MHDebate — a panel that argues so you can think",
  description:
    "Describe something you're trying to understand about mental health. A panel of perspectives gives you their honest disagreement in plain language. Not a diagnosis.",
};

const NAV = [
  { href: "/", label: "Ask" },
  { href: "/voices", label: "The panel" },
  { href: "/how-it-works", label: "How it works" },
  { href: "/support", label: "Get support" },
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen antialiased">
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 focus:rounded-lg focus:bg-surface focus:px-4 focus:py-2 focus:shadow-lg"
        >
          Skip to content
        </a>

        <header className="border-b border-line bg-surface/70 backdrop-blur">
          <div className="mx-auto flex max-w-5xl flex-wrap items-center justify-between gap-x-8 gap-y-3 px-5 py-4">
            <Link href="/" className="font-display text-xl tracking-tight">
              MH<span className="text-accent">Debate</span>
            </Link>
            <nav aria-label="Main" className="flex flex-wrap gap-x-5 gap-y-1 text-sm text-muted">
              {NAV.map((item) => (
                <Link key={item.href} href={item.href} className="transition-colors hover:text-ink">
                  {item.label}
                </Link>
              ))}
            </nav>
          </div>
        </header>

        <main id="main" className="mx-auto max-w-5xl px-5 py-10 sm:py-14">
          {children}
        </main>

        <footer className="mt-16 border-t border-line">
          <div className="mx-auto max-w-5xl space-y-3 px-5 py-8 text-sm text-muted">
            <p className="max-w-prose">
              MHDebate is an educational tool. It does not diagnose, does not treat, and is not a
              substitute for a professional who can actually ask you questions back. Every voice
              here is generated by the same AI model, so agreement between them is weak evidence.
            </p>
            <p>
              If you are in crisis,{" "}
              <Link href="/support" className="text-accent underline underline-offset-2">
                these numbers connect to a person
              </Link>
              .
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
