import type { RiskLevel, RiskTopic } from "./safety";
import type { ClinicalSummary, PanelChoice, PanelRequest } from "./types";

/**
 * The document model that both the PDF writer and the plain-text export render
 * from, so the two can never drift into saying different things.
 *
 * Everything here is deterministic. The only model-authored content is what
 * arrives inside `ClinicalSummary`; the framing, the verbatim quote, the safety
 * note, and every disclaimer are assembled in code, where they cannot be
 * paraphrased into something weaker.
 */

export type Block =
  | { kind: "title"; text: string }
  | { kind: "meta"; text: string }
  | { kind: "banner"; lines: string[] }
  | { kind: "heading"; text: string }
  | { kind: "subheading"; text: string }
  | { kind: "paragraph"; text: string }
  | { kind: "quote"; text: string }
  | { kind: "bullets"; items: string[] }
  | { kind: "rule" };

export interface ReportDoc {
  title: string;
  /** Runs along the bottom of every page. */
  footer: string;
  blocks: Block[];
}

export interface ReportInput {
  request: PanelRequest;
  panel: PanelChoice | null;
  clinical: ClinicalSummary;
  riskLevel: RiskLevel;
  riskTopics: RiskTopic[];
  /** Passed in rather than read from the clock, so output is reproducible. */
  generatedAt: Date;
}

const ABOUT_LINE: Record<PanelRequest["about"], string> = {
  me: "Written by the patient about themselves.",
  "someone-i-care-about": "Written by someone close to the patient, not by the patient.",
  "a-child-or-teen": "Written by an adult about a child or teenager in their care.",
};

/** Deterministic, and honest about what kind of check it actually was. */
export function safetyNote(level: RiskLevel, topics: RiskTopic[]): string {
  const caveat =
    "This is an automated keyword screen run before the discussion was generated. It is not a risk assessment and no risk assessment has been carried out.";

  switch (level) {
    case "crisis":
      // Unreachable in practice — a crisis screen stops the debate before any
      // of this exists — but stated rather than assumed away.
      return `Screen flagged language indicating possible immediate risk. No discussion was generated. ${caveat}`;
    case "concern":
      return `Screen flagged reference to suicide or self-harm without stated current intent. Crisis resources were shown, and the patient chose to continue. ${caveat}`;
    case "sensitive":
      return `Screen flagged sensitive content (${topics.join(", ")}). Relevant support resources were shown alongside the discussion. ${caveat}`;
    default:
      return `Screen found no crisis indicators. ${caveat}`;
  }
}

function formatDate(date: Date): string {
  return date.toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
}

export function buildClinicalReport(input: ReportInput): ReportDoc {
  const { clinical, request, generatedAt } = input;
  const blocks: Block[] = [];

  blocks.push({ kind: "title", text: "Notes to bring to an appointment" });
  blocks.push({
    kind: "meta",
    text: `Prepared ${formatDate(generatedAt)} · ${ABOUT_LINE[request.about]}`,
  });

  blocks.push({
    kind: "banner",
    lines: [
      "NOT A CLINICAL DOCUMENT.",
      "Generated by MHDebate, an AI tool, from the few sentences quoted below and nothing else.",
      "No history was taken, nothing was examined, no records were seen, and no diagnosis is offered or implied.",
      "It carries no clinical authority. Treat it as a structured version of what the patient wanted to tell you.",
    ],
  });

  blocks.push({ kind: "heading", text: "In the patient's own words" });
  blocks.push({ kind: "paragraph", text: "Reproduced exactly as written, unedited:" });
  blocks.push({ kind: "quote", text: request.question.trim() });

  if (clinical.reasonForContact) {
    blocks.push({ kind: "heading", text: "Reason for contact" });
    blocks.push({ kind: "paragraph", text: clinical.reasonForContact });
  }

  if (clinical.history.length) {
    blocks.push({ kind: "heading", text: "History as reported" });
    blocks.push({ kind: "bullets", items: clinical.history });
  }

  if (clinical.functionalImpact.length) {
    blocks.push({ kind: "heading", text: "Functional impact as reported" });
    blocks.push({ kind: "bullets", items: clinical.functionalImpact });
  }

  if (clinical.triedAlready.length) {
    blocks.push({ kind: "heading", text: "Already tried" });
    blocks.push({ kind: "bullets", items: clinical.triedAlready });
  }

  if (clinical.areasToExplore.length) {
    blocks.push({ kind: "heading", text: "Areas the discussion raised" });
    blocks.push({
      kind: "paragraph",
      text: "Deliberately phrased as domains and questions rather than as a differential. This tool does not diagnose, and a label it generated is not one the patient has earned.",
    });
    for (const area of clinical.areasToExplore) {
      blocks.push({ kind: "subheading", text: area.area });
      if (area.whyRaised) blocks.push({ kind: "paragraph", text: area.whyRaised });
      if (area.discriminators.length) {
        blocks.push({ kind: "bullets", items: area.discriminators });
      }
    }
  }

  if (clinical.worthExcluding.length) {
    blocks.push({ kind: "heading", text: "Ordinary contributors worth excluding" });
    blocks.push({ kind: "bullets", items: clinical.worthExcluding });
  }

  if (clinical.whatTheyreAskingFor.length) {
    blocks.push({ kind: "heading", text: "What the patient appears to be asking for" });
    blocks.push({ kind: "bullets", items: clinical.whatTheyreAskingFor });
  }

  blocks.push({ kind: "heading", text: "Safety screen" });
  blocks.push({ kind: "paragraph", text: safetyNote(input.riskLevel, input.riskTopics) });

  blocks.push({ kind: "heading", text: "What this document is not" });
  blocks.push({
    kind: "bullets",
    items: [
      "Not an assessment. No history was taken and no examination was performed.",
      "Not a referral, and not written or reviewed by any clinician.",
      "Not corroborated. Nothing here was checked against records, collateral history, or anyone else's account.",
      "Not a differential. Any condition that fits was deliberately left unnamed.",
      "Not complete. It reflects only what the patient chose to type into a text box on one occasion.",
    ],
  });

  blocks.push({ kind: "rule" });
  blocks.push({
    kind: "paragraph",
    text: "Generated by MHDebate. The discussion behind this page was produced by several AI perspectives that all run on the same underlying model, so agreement between them is not corroboration. Nothing was stored: this document exists only where the patient saved it.",
  });

  return {
    title: "Notes to bring to an appointment",
    footer: "MHDebate · AI-generated from patient self-report · not a clinical document",
    blocks,
  };
}

/** Plain-text rendering, for pasting into a portal message or an email. */
export function renderReportText(doc: ReportDoc): string {
  const out: string[] = [];

  for (const block of doc.blocks) {
    switch (block.kind) {
      case "title":
        out.push(block.text.toUpperCase(), "=".repeat(block.text.length), "");
        break;
      case "meta":
        out.push(block.text, "");
        break;
      case "banner":
        out.push(...block.lines.map((line) => `! ${line}`), "");
        break;
      case "heading":
        out.push("", block.text.toUpperCase(), "-".repeat(block.text.length));
        break;
      case "subheading":
        out.push("", `* ${block.text}`);
        break;
      case "paragraph":
        out.push(block.text);
        break;
      case "quote":
        out.push(...block.text.split("\n").map((line) => `  | ${line}`));
        break;
      case "bullets":
        out.push(...block.items.map((item) => `  - ${item}`));
        break;
      case "rule":
        out.push("", "-".repeat(60));
        break;
    }
  }

  out.push("", doc.footer);
  return out.join("\n").replace(/\n{3,}/g, "\n\n").trim() + "\n";
}

/** A filename that says what it is without naming the person. */
export function reportFilename(generatedAt: Date): string {
  const stamp = generatedAt.toISOString().slice(0, 10);
  return `appointment-notes-${stamp}.pdf`;
}
